#---------------------------------------------------
# Composite action (Setup Self-hosted Runner without Docker)
#---------------------------------------------------
name: Setup Dynamic Self-hosted Linux Runner
description: Composite action to register GitHub Actions runner on host directly

inputs:
  artifactory_url:
    required: true
    description: "Artifactory base URL"

  artifactory_username:
    required: true
    description: "Artifactory Authentication Username"

  artifactory_password:
    required: true
    description: "Artifactory Authentication Password"

  runner_setup_path:
    required: true
    description: "Artifactory path of Actions Runner tar.gz for Linux"

  workflow_ci_token:
    required: true
    description: "GitHub PAT with repo actions:write"

outputs:
  label:
    value: ${{ steps.generate_label.outputs.label }}
    description: "Unique label assigned to the dynamic GitHub runner"

  runs_on:
    value: ${{ steps.generate_label.outputs.runs_on }}
    description: "JSON array of runner labels to be used in the 'runs-on' field"

runs:
  using: "composite"
  steps:

    - name: Generate dynamic runner label
      id: generate_label
      shell: bash
      run: |
        echo "🔧 Generating unique runner label..."
        RANDOM_SUFFIX=$(printf "%05d%05d" $RANDOM $RANDOM)
        # LABEL="host-${GITHUB_REPOSITORY##*/}-${GITHUB_RUN_NUMBER}-${RANDOM_SUFFIX}"
        LABEL="reporunner"
        RUNS_ON="[\"self-hosted\", \"${LABEL}\"]"

        echo "label=${LABEL}" >> $GITHUB_OUTPUT
        echo "runs_on=${RUNS_ON}" >> $GITHUB_OUTPUT

    - name: Download GitHub Actions runner package
      shell: bash
      run: |
        echo " Creating directory for runner: actions-runner-${{ steps.generate_label.outputs.label }}"
        mkdir -p actions-runner-${{ steps.generate_label.outputs.label }}
        cd actions-runner-${{ steps.generate_label.outputs.label }}
        
        echo "📦 Downloading runner from Artifactory..."
        curl -u "${{ inputs.artifactory_username }}:${{ inputs.artifactory_password }}" \
             -O "${{ inputs.artifactory_url }}/${{ inputs.runner_setup_path }}"
        echo "📂 Extracting tarfile..."
        tar -xzf ./actions-runner-linux-x64-*.tar.gz


    - name: Configure the runner
      shell: bash
      run: |
        echo "⚙️ Configuring the GitHub runner..."
        cd actions-runner-${{ steps.generate_label.outputs.label }}

        ./config.sh --unattended \
          --url "https://github.com/${GITHUB_REPOSITORY}" \
          --token "${{ inputs.workflow_ci_token }}" \
          --name "${{ steps.generate_label.outputs.label }}" \
          --labels "${{ steps.generate_label.outputs.label }}" \
          --work _work
       echo "✅ Runner configured successfully."

    - name: Start the runner in background
      shell: bash
      run: |
        cd actions-runner-${{ steps.generate_label.outputs.label }}
        nohup ./run.sh &
