name: Reusable Parasoft SCA Workflow

on:
  workflow_call:
    inputs:
      runner_version:
        description: "Runner version to install"
        required: true
        type: string
      git_ref_name:
        required: true
        type: string
      ruleset:
        required: true
        type: string

jobs:
  setup_runner:
    runs-on: [self-hosted, matrix-comsec-pvt-ltd]
    outputs:
      label: ${{ steps.start_runner.outputs.label }}
      runs_on: ${{ steps.start_runner.outputs.runs_on }}
    steps:
      - name: Setup Dynamic Host Runner
        id: start_runner
        uses: matrix-comsec-pvt-ltd/sca/.github/actions/setup-linux-parasoft-sca-runner@main
        with:
          runner_version: ${{ inputs.runner_version }}
          workflow_ci_token: ${{ secrets.WORKFLOW_CI_TOKEN }}
          artifactory_url: ${{ vars.ARTIFACTORY_URL }}
          artifactory_username: ${{ secrets.ARTIFACTORY_USERNAME }}
          artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          runner_setup_path: ${{ vars.ARTIFACTORY_LINUX_RUNNER_SETUP }}
  
  run_on_dynamic:
    needs: setup_runner
    runs-on: ${{ fromJSON(needs.setup_runner.outputs.runs_on) }}
    steps:
      - name: Print current user
        run: whoami

  teardown_runner:
    #if: always()
    needs: [setup_runner, run_on_dynamic]
    runs-on: [self-hosted, matrix-comsec-pvt-ltd]
    steps:
      - name: Stop and remove runner
        uses: matrix-comsec-pvt-ltd/sca/.github/actions/remove-linux-parasoft-sca-runner@main
        with:
          label: ${{ needs.setup_runner.outputs.label }}
          runner_dir: ${{ needs.setup_runner.outputs.runner_dir }}
