name: Debug Runner Identity

on:
  workflow_dispatch:

jobs:
  print_user:
    # runs-on: ${{ fromJSON(vars.ORGANIZATION_RUNNER_LABEL) }}
    runs-on: [self-hosted, matrix-comsec-pvt-ltd] 
    steps:
      - name: Print runner user
        run: whoami
